baseURL = 'https://sojunie.github.io'
languageCode = 'en-us'
title = 'Seojun Blog'
theme = 'hugo-simple'
copyright = "© 2025 Seojun Cha"
enableRobotsTXT = true

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Blog"
pageRef = "/blog"
weight = 20

[markup.highlight]
noClasses = true
tabWidth = 2
style = "xcode-dark"

[params]
env = "production"
comments = true

